# -*- coding: utf-8 -*-
"""homework9

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zUmZ53DFSCSmp5kssDh85oKgKrb0BK6d
"""

import pandas as pd



df = pd.read_csv('sample_data/california_housing_train.csv')

"""Задача 40. 
Определить среднюю стоимость дома (median_house_value), где кол-во людей от 0 до 500 (population).
"""

df[(df['population'])>=0 & (df['population']<=500)]['median_house_value'].mean()

"""Задача 42:
Узнать какая максимальная households в зоне минимального значения population.

"""

df[df['population'] < df['population'].quantile(.25)]['households'].max()